### ISSUE TITLE
`ZkNewFromTitleSelection` does not copy last character correctly if it's non-ascii

### ISSUE THREAD

**Issue by iAurora** [zk-org/zk-nvim#179] opened 2024-07-18 03:59 UTC
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Same problem #125 reports, in my case the character is Cyrillic. 

The created title ends with � and there is extra code left after the link in original note. 

### How to reproduce?

1. Add a note with content: "Текст заголовка"
2. Visually select "Текст заголовка"
3. Run `:'<,'>ZkNewFromTitleSelection`
4. Check the title of the newly created file
5. Check the link inserted in the original file

<img width="425" alt="Screenshot 2024-07-18 at 05 21 48" src="https://github.com/user-attachments/assets/88d3d22a-dc43-4bc1-9af1-171205804d88">

<img width="425" alt="Screenshot 2024-07-18 at 05 22 17" src="https://github.com/user-attachments/assets/5a03416e-f0c0-465b-b75a-029f110be904">

<img width="425" alt="Screenshot 2024-07-18 at 05 22 37" src="https://github.com/user-attachments/assets/5cd7ec52-47c0-4480-a3b7-d2d7773800cb">

### zk configuration

```toml
# NOTE SETTINGS

# Defines the default options used when generating new notes.
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "ru"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
# filename = "{{format-date now '%Y%m%d%H%M%S'}}"
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"

# Path globs ignored while indexing existing notes.
ignore = [
  ".obsidian",
	"templates"
]


# EXTRA VARIABLES
#
# A dictionary of variables you can use for any custom values when generating
# new notes. They are accessible in templates with {{extra.<key>}}
[extra]

#key = "value"


# GROUP OVERRIDES
[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "journal.md"


# MARKDOWN SETTINGS
[format.markdown]

# Format used to generate links between notes.
# Either "wiki", "markdown" or a custom template. Default is "markdown".
link-format = "wiki"
# Indicates whether a link's path will be percent-encoded.
# Defaults to true for "markdown" format and false for "wiki" format.
link-encode-path = true
# Indicates whether a link's path file extension will be removed.
# Defaults to true.
link-drop-extension = true

# Enable support for #hashtags.
hashtags = true
# Enable support for :colon:separated:tags:.
colon-tags = false
# Enable support for Bear's #multi-word tags#
# Hashtags must be enabled for multi-word tags to work.
multiword-tags = false


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes. When not set, the EDITOR or VISUAL
# environment variables are used.
editor = "nvim"

# Pager used to scroll through long output. If you want to disable paging
# altogether, set it to an empty string "".
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"


# LSP
#
#   Configure basic editor integration for LSP-compatible editors.
#   See https://github.com/zk-org/zk/blob/main/docs/editors-integration.md
#
[lsp]

[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
#wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"

[lsp.completion]
# Customize the completion pop-up of your LSP client.

# Show the note title in the completion pop-up, or fallback on its path if empty.
note-label = "{{title-or-path}}"
# Filter out the completion pop-up using the note title or its path.
note-filter-text = "{{title}} {{path}}"
# Show the note filename without extension as detail.
note-detail = ""
```

### Neovim configuration

```viml
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
  spec = {
    -- add your plugins here
    {
        "zk-org/zk-nvim",
        config = function()
          require("zk").setup({
            -- See Setup section below
	    picker = select,

      lsp = {
        -- `config` is passed to `vim.lsp.start_client(config)`
        config = {
          cmd = { "zk", "lsp" },
          name = "zk",
          -- on_attach = ...
          -- etc, see `:h vim.lsp.start_client()`
        },

        -- automatically attach buffers in a zk notebook that match the given filetypes
        auto_attach = {
          enabled = true,
          filetypes = { "markdown" },
        },
      },
          })
        end
      }
  },
  -- Configure any other settings here. See the documentation for more details.
  -- colorscheme that will be used when installing plugins.
  install = { colorscheme = { "habamax" } },
  -- automatically check for plugin updates
  checker = { enabled = true },
})
```

### Environment

```bash
zk 0.14.1
system: Darwin 23.4.0 x86_64
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
```

**Comment by tjex** [comment] 2024-07-18 07:55
I can confirm that when I copy and paste the text, and use it as the title of a new note, that I get the same errors as you report.

However, if I replace the 'a' with a regular typed 'a', there is no error. 
I'm completely ignorant to Cryllic, and only a little learned in Unicode... 
So I have to ask, is there a difference between the 'a' in "Текст заголовка" and a Latin 'a'?
As I see the 'k" has a different shape than a Latin 'k' from my keyboard, yet the 'a' looks identical to my eyes.

As, if I inspect the value of the letter in neovim:

The copy and pasted 'a' returns: `<a>  97,  Hex 61,  Octal 141`
And the 'a' typed on my keyboard (Australian layout) returns: `<а> 1072, Hex 0430, Oct 2060, Digr a=`

So if there is no difference between the shape / etc between Cryllic and Latin 'a', then it would seem your keyboard is outputting a different value for the same symbol. Which then makes me wonder where this bug would come from, whether it's from our side or the Cryllic language support in neovim / terminal?

It's interesting too, because the other 'a' in "Текст заголовка" is being rendered fine. So it would seem there's some conflict between the end of string data, and the ascii value your keyboard is using for 'a'...

Tested some cases:

* `Текст заголовка |` adding whitespace after the string, and including it in the highlighted text when making a new note: no error
* `Текст заголовка |` the same, but not including the white space in the highlighted text: error
* `Текст заголовiа` replace Cryllic 'k' with Latin 'i': error
* `Текст заголовкаi` add a Latin 'i' after the original 'buggy' 'a': no error

So there is something odd going on with the combination of the 'a' from your keyboard with the end of string data.
This could still be on our end. Perhaps we're chopping off some data when extracting the highlighted text. But damn... This is a pretty obscure bug and pretty beyond my paygrade... I'm not sure I can handle this in any timely manner and am hoping one of the other maintainers has some easy clarifications at hand...

**Comment by tjex** [comment] 2024-07-18 08:04
From `:h unicode`

> Bytes which are not part of a valid UTF-8 byte sequence are handled like a
single character and displayed as <xx>, where "xx" is the hex value of the
byte.

And the byte in our case being: `<b0>`

**Comment by iAurora** [comment] 2024-07-18 08:58
While Latin `a` and Cyrillic `а` look similar, they are parts of two completely different charsets. Cyrillic is a separate writing system in the same way Korean hangul or Greek alphabet are. It is outside of regular ASCII range and can be only found in extended sets. It does fit UTF-8.

You can ignore my example and use `Фывя злдж`, which are all Cyrillic letters that look nothing like Latin alphabet and they will all render fine except the last `ж`. #125 had exactly same issue with Japanese Hiragana and Emoji, so it's not an obscure bug with some particular character but rather an issue with the last character of the title in a non-Latin based language.

**Comment by tjex** [comment] 2024-07-19 11:25
Ok cool, thanks for the extra info and context 👍

**Comment by tjex** [comment] 2024-09-10 19:29
@whynothugo 
I just saw your blog post about non-english characters. And it was quite extensive. Would you have any immediate insights here by chance? 😇

**Comment by WhyNotHugo** [comment] 2024-09-10 20:51
I don't use the neovim plugin, but I do use the LSP. My own repro steps:

- Type `Текст заголовка`
- Select the whole line (shift+v)
- Trigger code action `New note in current directory`

This is what renders:

    [Текст заголовка](yfl6)<b3>оловка

The input text is 15 characters and 29 bytes:

```
Т 1058 0x422
е 1077 0x435
к 1082 0x43a
с 1089 0x441
т 1090 0x442
  32 0x20
з 1079 0x437
а 1072 0x430
г 1075 0x433
о 1086 0x43e
л 1083 0x43b
о 1086 0x43e
в 1074 0x432
к 1082 0x43a
а 1072 0x430
```

There are 13 trailing characters after the link's closing parenthesis. They are the last 13 characters from the input string. The first byte is not valid utf-8, the rest are the last six characters from the input.

Those 13 characters are as follows:

```
(invalid utf) 179 0xb3
о 1086 0x43e
л 1083 0x43b
о 1086 0x43e
в 1074 0x432
к 1082 0x43a
а 1072 0x430
```

I suspect that the LSP returns an invalid result. Log messages between neovim and the LSP, and check if the response is already corrupted at that point.

Tip: `vim.lsp.set_log_level("debug")`.

## Useless trivia

The output that I expect from the LSP should have been 37 bytes, but it's 50 bytes.

**Comment by WhyNotHugo** [comment] 2024-09-10 21:09
Ugh, my above test seems to have been messed up by selecting the hole line. Looks like my issue was caused by the trailing newline in the selection. Totally unrelated bug.

I can't repro by calling the LSP action, so I suspect the issue is the plugin itself.

**Comment by WhyNotHugo** [comment] 2024-09-11 08:10
In my case, this is the response that returns from the LSP:

    [DEBUG][2024-09-11 10:00:01] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 0,  jsonrpc = "2.0",  method = "workspace/applyEdit",  params = {    edit = {      changes = {        ["file:///home/hugo/zk/test.md"] = { {            newText = "[Текст заголовка](huuh)",            range = {              ["end"] = {                character = 16,                line = 0              },              start = {                character = 0,                line = 0              }            }          } }      }    }  }}

It indicates that the client should replace the first 16 characters in the file with the string `[Текст заголовка](huuh)`.

If we replace the first sixteen **bytes** instead of the first 16 characters, the result is exactly what neovim is producing.

So the issue that I'm seeing seems to be a bug in neovim, and entirely unrelated to op's issue.

**Comment by WhyNotHugo** [comment] 2024-09-11 08:24
The exact meaning of these positions is negotiated between the client and server, but the default is UTF-16: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position

This is because LSP has origins in JavaScript world, which uses this encoding by default. Nobody else (except Java?) uses this.

This is also what neovim and the LSP agree on in this case:

    [DEBUG][2024-09-11 10:17:59] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      general = {        positionEncodings = { "utf-16" }      },      textDocument = {        callHierarchy = {          dynamicRegistration = false        },        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }            }          },          dataSupport = true,          dynamicRegistration = true,          isPreferredSupport = true,          resolveSupport = {            properties = { "edit" }          }        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }          },          completionList = {            itemDefaults = { "editRange", "insertTextFormat", "insertTextMode", "data" }          },          contextSupport = false,          dynamicRegistration = false        },        declaration = {          linkSupport = true        },        definition = {          dynamicRegistration = true,          linkSupport = true        },        diagnostic = {          dynamicRegistration = false        },        documentHighlight = {          dynamicRegistration = false        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        formatting = {          dynamicRegistration = true        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = true        },        implementation = {          linkSupport = true        },        inlayHint = {          dynamicRegistration = true,          resolveSupport = {            properties = { "textEdits", "tooltip", "location", "c

In UTF-16, the input string is 32bytes long. 

Neovim says the range ends at 28. This index is zero-based, so neovim is telling the LSP "apply this action on this range of length 29".

The selected text is "of length 29" if you encode in utf-8, but in utf-16, it should be of length 32.

Neovim needs to re-encode the text into utf-16 to send the proper length **or** negotiate utf-8 with the server. The problem is that support for utf-8 is not mandatory per the specification, because that would make life too simple.

**Comment by WhyNotHugo** [comment] 2024-09-11 08:39
I inspected the value returned by:

https://github.com/zk-org/zk-nvim/blob/main/lua/zk/commands/builtin.lua#L21

And it returns:

```
{                                                                                                                 
  range = {                                                                                                       
    ["end"] = {                                                                                                   
      character = 28,                                                                                             
      line = 0                                                                                                    
    },                                                                                                            
    start = {                                                                                                     
      character = 0,                                                                                              
      line = 0                                                                                                    
    }                                                                                                             
  },                                                                                                              
  uri = "file:///home/hugo/zk/test.md"                                                                            
}                                                                                                                 
```

If I understand correctly, this function needs to return indexes in utf-16 code points, but this is the index in bytes.

**Comment by WhyNotHugo** [comment] 2024-09-11 08:41
I added `print(selected_text)` on the value that the plugin sends to the LSP:

https://github.com/zk-org/zk-nvim/blob/dbf4eeab55b08856c9d6b6722dbff39630bb35eb/lua/zk/commands/builtin.lua#L22

And it prints:

    Текст заголовк<d0>

This is missing the last byte. It is not entirely clear to me why.

**Comment by WhyNotHugo** [comment] 2024-09-11 08:45
We probably want to use `vim.region` here instead.

**Comment by WhyNotHugo** [comment] 2024-09-11 09:00
This patch fixes the text for the newly created note, but the link to it still has a trailing broken byte:

```diff
diff --git a/lua/zk/util.lua b/lua/zk/util.lua
index 70f9701..43c15b6 100644
--- a/lua/zk/util.lua
+++ b/lua/zk/util.lua
@@ -100,13 +100,15 @@ function M.get_text_in_range(range)
   local A = range["start"]
   local B = range["end"]
 
-  local lines = vim.api.nvim_buf_get_lines(0, A.line, B.line + 1, true)
-  if vim.tbl_isempty(lines) then
-    return nil
+  local region = vim.region(0, { A.line, A.character }, { B.line, B.character }, vim.fn.visualmode(), true)
+
+  local lines = {}
+  local maxcol = vim.v.maxcol
+  for line, cols in vim.spairs(region) do
+    local endcol = cols[2] == maxcol and -1 or cols[2]
+    local chunk = vim.api.nvim_buf_get_text(0, line, cols[1], line, endcol, {})[1]
+    table.insert(lines, chunk)
   end
-  local MAX_STRING_SUB_INDEX = 2 ^ 31 - 1 -- LuaJIT only supports 32bit integers for `string.sub` (in block selection B.character is 2^31)
-  lines[#lines] = string.sub(lines[#lines], 1, math.min(B.character, MAX_STRING_SUB_INDEX))
-  lines[1] = string.sub(lines[1], math.min(A.character + 1, MAX_STRING_SUB_INDEX))
   return table.concat(lines, "\n")
 end
```

**Comment by WhyNotHugo** [comment] 2024-09-11 09:16
See: https://github.com/zk-org/zk-nvim/pull/187

The LSP still sends a trailing invalid byte after the link that is inserted. I don't know why this happens, but my impression is that when neovim replaces the original text, it replaces up to the first byte in the last character, and the second byte in that character is left behind.

**Comment by WhyNotHugo** [comment] 2024-09-11 09:30
Regarding the scenario where I selected the trailing newline, from the LSP spec:

> If the character value is greater than the line length it defaults back to the line length.

I think this is what happened in my case, the line length seems to be calculated by counting characters, but the replacement applied counting bytes.

**Comment by WhyNotHugo** [comment] 2024-09-11 09:31
As per my understanding of [how positions are supposed to work in the language server protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position), a lot of the indexes being exchanged are wrong. Both neovim and the LSP are counting octets instead of code units. At least one of the following is true:

- Both neovim and the LSP are doing something slightly wrong, but align with one another.
- My understanding of the above link is mistaken.

**Comment by tjex** [comment] 2024-09-12 16:42
Outstanding!!!

**Closed** 2024-09-18 19:22 UTC
Labels: help wanted
